-- ============================================================
-- SEED: Country Master reference (static data)
-- Source: GeoNames countryInfo.txt, via Country_Master_Extended_Filled.xlsx
-- Run AFTER migration_18.sql, in Supabase -> SQL Editor -> Run.
-- Safe to re-run -- upserts by iso2.
-- ============================================================

insert into country_master (iso2, country_en, country_de, continent_en, continent_de, languages_en, languages_de, language_codes, capital, currency, official_languages)
values
  ('AD', 'Andorra', 'Andorra', 'Europe', 'Europa', 'Catalan', 'Katalanisch', 'ca', 'Andorra la Vella', 'EUR', 'Catalan'),
  ('AE', 'United Arab Emirates', 'Vereinigte Arabische Emirate', 'Asia', 'Asien', 'Arabic, Persian, English, Hindi, Urdu', 'Arabisch, Persisch, Englisch, Hindi, Urdu', 'ar, fa, en, hi, ur', 'Abu Dhabi', 'AED', 'Arabic, Persian, English, Hindi, Urdu'),
  ('AF', 'Afghanistan', 'Afghanistan', 'Asia', 'Asien', 'Persian, Pushto, Uzbek, Turkmen', 'Persisch, Paschtu, Usbekisch, Turkmenisch', 'fa, ps, uz, tk', 'Kabul', 'AFN', 'Persian, Pushto, Uzbek, Turkmen'),
  ('AG', 'Antigua and Barbuda', 'Antigua und Barbuda', 'North America', 'Nordamerika', 'English', 'Englisch', 'en', 'St. John''s', 'XCD', 'English'),
  ('AI', 'Anguilla', 'Anguilla', 'North America', 'Nordamerika', 'English', 'Englisch', 'en', 'The Valley', 'XCD', 'English'),
  ('AL', 'Albania', 'Albanien', 'Europe', 'Europa', 'Albanian, Modern Greek (1453-)', 'Albanisch, Griechisch', 'sq, el', 'Tirana', 'ALL', 'Albanian, Modern Greek (1453-)'),
  ('AM', 'Armenia', 'Armenien', 'Asia', 'Asien', 'Armenian', 'Armenisch', 'hy', 'Yerevan', 'AMD', 'Armenian'),
  ('AO', 'Angola', 'Angola', 'Africa', 'Afrika', 'Portuguese', 'Portugiesisch', 'pt', 'Luanda', 'AOA', 'Portuguese'),
  ('AQ', 'Antarctica', 'Antarktis', 'Antarctica', 'Antarktika', null, null, null, null, null, null),
  ('AR', 'Argentina', 'Argentinien', 'South America', 'Südamerika', 'Spanish, English, Italian, German, French, Guarani', 'Spanisch, Englisch, Italienisch, Deutsch, Französisch, Guaraní', 'es, en, it, de, fr, gn', 'Buenos Aires', 'ARS', 'Spanish, English, Italian, German, French, Guarani'),
  ('AS', 'American Samoa', 'Amerikanisch-Samoa', 'Oceania', 'Ozeanien', 'English, Samoan, Tonga (Tonga Islands)', 'Englisch, Samoanisch, Tongaisch', 'en, sm, to', 'Pago Pago', 'USD', 'English, Samoan, Tonga (Tonga Islands)'),
  ('AT', 'Austria', 'Österreich', 'Europe', 'Europa', 'German, Croatian, Hungarian, Slovenian', 'Deutsch, Kroatisch, Ungarisch, Slowenisch', 'de, hr, hu, sl', 'Vienna', 'EUR', 'German, Croatian, Hungarian, Slovenian'),
  ('AU', 'Australia', 'Australien', 'Oceania', 'Ozeanien', 'English', 'Englisch', 'en', 'Canberra', 'AUD', 'English'),
  ('AW', 'Aruba', 'Aruba', 'North America', 'Nordamerika', 'Dutch, Papiamento, Spanish, English', 'Niederländisch, Papiamento, Spanisch, Englisch', 'nl, pap, es, en', 'Oranjestad', 'AWG', 'Dutch, Papiamento, Spanish, English'),
  ('AX', 'Aland Islands', 'Ålandinseln', 'Europe', 'Europa', 'Swedish', 'Schwedisch', 'sv', 'Mariehamn', 'EUR', 'Swedish'),
  ('AZ', 'Azerbaijan', 'Aserbaidschan', 'Asia', 'Asien', 'Azerbaijani, Russian, Armenian', 'Aserbaidschanisch, Russisch, Armenisch', 'az, ru, hy', 'Baku', 'AZN', 'Azerbaijani, Russian, Armenian'),
  ('BA', 'Bosnia and Herzegovina', 'Bosnien und Herzegowina', 'Europe', 'Europa', 'Bosnian, Croatian, Serbian', 'Bosnisch, Kroatisch, Serbisch', 'bs, hr, sr', 'Sarajevo', 'BAM', 'Bosnian, Croatian, Serbian'),
  ('BB', 'Barbados', 'Barbados', 'North America', 'Nordamerika', 'English', 'Englisch', 'en', 'Bridgetown', 'BBD', 'English'),
  ('BD', 'Bangladesh', 'Bangladesch', 'Asia', 'Asien', 'Bengali, English', 'Bengalisch, Englisch', 'bn, en', 'Dhaka', 'BDT', 'Bengali, English'),
  ('BE', 'Belgium', 'Belgien', 'Europe', 'Europa', 'Dutch, French, German', 'Niederländisch, Französisch, Deutsch', 'nl, fr, de', 'Brussels', 'EUR', 'Dutch, French, German'),
  ('BF', 'Burkina Faso', 'Burkina Faso', 'Africa', 'Afrika', 'French, Mossi', 'Französisch, Mossi', 'fr, mos', 'Ouagadougou', 'XOF', 'French, Mossi'),
  ('BG', 'Bulgaria', 'Bulgarien', 'Europe', 'Europa', 'Bulgarian, Turkish, Romany', 'Bulgarisch, Türkisch, Romani', 'bg, tr, rom', 'Sofia', 'BGN', 'Bulgarian, Turkish, Romany'),
  ('BH', 'Bahrain', 'Bahrain', 'Asia', 'Asien', 'Arabic, English, Persian, Urdu', 'Arabisch, Englisch, Persisch, Urdu', 'ar, en, fa, ur', 'Manama', 'BHD', 'Arabic, English, Persian, Urdu'),
  ('BI', 'Burundi', 'Burundi', 'Africa', 'Afrika', 'French, Rundi', 'Französisch, Rundi', 'fr, rn', 'Gitega', 'BIF', 'French, Rundi'),
  ('BJ', 'Benin', 'Benin', 'Africa', 'Afrika', 'French', 'Französisch', 'fr', 'Porto-Novo', 'XOF', 'French'),
  ('BL', 'Saint Barthelemy', 'St. Barthélemy', 'North America', 'Nordamerika', 'French', 'Französisch', 'fr', 'Gustavia', 'EUR', 'French'),
  ('BM', 'Bermuda', 'Bermuda', 'North America', 'Nordamerika', 'English, Portuguese', 'Englisch, Portugiesisch', 'en, pt', 'Hamilton', 'BMD', 'English, Portuguese'),
  ('BN', 'Brunei', 'Brunei Darussalam', 'Asia', 'Asien', 'Malay (macrolanguage), English', 'Malaiisch, Englisch', 'ms, en', 'Bandar Seri Begawan', 'BND', 'Malay (macrolanguage), English'),
  ('BO', 'Bolivia', 'Bolivien', 'South America', 'Südamerika', 'Spanish, Quechua, Aymara', 'Spanisch, Quechua, Aymara', 'es, qu, ay', 'Sucre', 'BOB', 'Spanish, Quechua, Aymara'),
  ('BQ', 'Bonaire, Saint Eustatius and Saba ', 'Karibische Niederlande', 'North America', 'Nordamerika', 'Dutch, Papiamento, English', 'Niederländisch, Papiamento, Englisch', 'nl, pap, en', null, 'USD', 'Dutch, Papiamento, English'),
  ('BR', 'Brazil', 'Brasilien', 'South America', 'Südamerika', 'Portuguese, Spanish, English, French', 'Portugiesisch, Spanisch, Englisch, Französisch', 'pt, es, en, fr', 'Brasilia', 'BRL', 'Portuguese, Spanish, English, French'),
  ('BS', 'Bahamas', 'Bahamas', 'North America', 'Nordamerika', 'English', 'Englisch', 'en', 'Nassau', 'BSD', 'English'),
  ('BT', 'Bhutan', 'Bhutan', 'Asia', 'Asien', 'Dzongkha', 'Dzongkha', 'dz', 'Thimphu', 'BTN', 'Dzongkha'),
  ('BV', 'Bouvet Island', 'Bouvetinsel', 'Antarctica', 'Antarktika', null, null, null, null, 'NOK', null),
  ('BW', 'Botswana', 'Botsuana', 'Africa', 'Afrika', 'English, Tswana', 'Englisch, Tswana', 'en, tn', 'Gaborone', 'BWP', 'English, Tswana'),
  ('BY', 'Belarus', 'Belarus', 'Europe', 'Europa', 'Belarusian, Russian', 'Belarussisch, Russisch', 'be, ru', 'Minsk', 'BYN', 'Belarusian, Russian'),
  ('BZ', 'Belize', 'Belize', 'North America', 'Nordamerika', 'English, Spanish', 'Englisch, Spanisch', 'en, es', 'Belmopan', 'BZD', 'English, Spanish'),
  ('CA', 'Canada', 'Kanada', 'North America', 'Nordamerika', 'English, French, Inuktitut', 'Englisch, Französisch, Inuktitut', 'en, fr, iu', 'Ottawa', 'CAD', 'English, French, Inuktitut'),
  ('CC', 'Cocos Islands', 'Kokosinseln', 'Asia', 'Asien', 'Malay (macrolanguage), English', 'Malaiisch, Englisch', 'ms, en', 'West Island', 'AUD', 'Malay (macrolanguage), English'),
  ('CD', 'Democratic Republic of the Congo', 'Kongo-Kinshasa', 'Africa', 'Afrika', 'French, Lingala, Kituba (Democratic Republic of Congo), Kongo, Swahili (macrolanguage), Luba-Lulua', 'Französisch, Lingala, Kituba (Democratic Republic of Congo), Kongolesisch, Suaheli, Luba-Lulua', 'fr, ln, ktu, kg, sw, lua', 'Kinshasa', 'CDF', 'French, Lingala, Kituba (Democratic Republic of Congo), Kongo, Swahili (macrolanguage), Luba-Lulua'),
  ('CF', 'Central African Republic', 'Zentralafrikanische Republik', 'Africa', 'Afrika', 'French, Sango, Lingala, Kongo', 'Französisch, Sango, Lingala, Kongolesisch', 'fr, sg, ln, kg', 'Bangui', 'XAF', 'French, Sango, Lingala, Kongo'),
  ('CG', 'Republic of the Congo', 'Kongo-Brazzaville', 'Africa', 'Afrika', 'French, Kongo, Lingala', 'Französisch, Kongolesisch, Lingala', 'fr, kg, ln', 'Brazzaville', 'XAF', 'French, Kongo, Lingala'),
  ('CH', 'Switzerland', 'Schweiz', 'Europe', 'Europa', 'German, French, Italian, Romansh', 'Deutsch, Französisch, Italienisch, Rätoromanisch', 'de, fr, it, rm', 'Bern', 'CHF', 'German, French, Italian, Romansh'),
  ('CI', 'Ivory Coast', 'Côte d’Ivoire', 'Africa', 'Afrika', 'French', 'Französisch', 'fr', 'Yamoussoukro', 'XOF', 'French'),
  ('CK', 'Cook Islands', 'Cookinseln', 'Oceania', 'Ozeanien', 'English, Maori', 'Englisch, Māori', 'en, mi', 'Avarua', 'NZD', 'English, Maori'),
  ('CL', 'Chile', 'Chile', 'South America', 'Südamerika', 'Spanish', 'Spanisch', 'es', 'Santiago', 'CLP', 'Spanish'),
  ('CM', 'Cameroon', 'Kamerun', 'Africa', 'Afrika', 'English, French', 'Englisch, Französisch', 'en, fr', 'Yaounde', 'XAF', 'English, French'),
  ('CN', 'China', 'China', 'Asia', 'Asien', 'Chinese, Yue Chinese, Wu Chinese, Daur, Uighur, Zhuang', 'Chinesisch, Kantonesisch, Wu, Daur, Uigurisch, Zhuang', 'zh, yue, wuu, dta, ug, za', 'Beijing', 'CNY', 'Chinese, Yue Chinese, Wu Chinese, Daur, Uighur, Zhuang'),
  ('CO', 'Colombia', 'Kolumbien', 'South America', 'Südamerika', 'Spanish', 'Spanisch', 'es', 'Bogota', 'COP', 'Spanish'),
  ('CR', 'Costa Rica', 'Costa Rica', 'North America', 'Nordamerika', 'Spanish, English', 'Spanisch, Englisch', 'es, en', 'San Jose', 'CRC', 'Spanish, English'),
  ('CU', 'Cuba', 'Kuba', 'North America', 'Nordamerika', 'Spanish, Papiamento', 'Spanisch, Papiamento', 'es, pap', 'Havana', 'CUP', 'Spanish, Papiamento'),
  ('CV', 'Cabo Verde', 'Cabo Verde', 'Africa', 'Afrika', 'Portuguese', 'Portugiesisch', 'pt', 'Praia', 'CVE', 'Portuguese'),
  ('CW', 'Curacao', 'Curaçao', 'North America', 'Nordamerika', 'Dutch, Papiamento', 'Niederländisch, Papiamento', 'nl, pap', ' Willemstad', 'XCG', 'Dutch, Papiamento'),
  ('CX', 'Christmas Island', 'Weihnachtsinsel', 'Oceania', 'Ozeanien', 'English, Chinese, Malay (macrolanguage)', 'Englisch, Chinesisch, Malaiisch', 'en, zh, ms', 'Flying Fish Cove', 'AUD', 'English, Chinese, Malay (macrolanguage)'),
  ('CY', 'Cyprus', 'Zypern', 'Europe', 'Europa', 'Modern Greek (1453-), Turkish, English', 'Griechisch, Türkisch, Englisch', 'el, tr, en', 'Nicosia', 'EUR', 'Modern Greek (1453-), Turkish, English'),
  ('CZ', 'Czechia', 'Tschechien', 'Europe', 'Europa', 'Czech, Slovak', 'Tschechisch, Slowakisch', 'cs, sk', 'Prague', 'CZK', 'Czech, Slovak'),
  ('DE', 'Germany', 'Deutschland', 'Europe', 'Europa', 'German', 'Deutsch', 'de', 'Berlin', 'EUR', 'German'),
  ('DJ', 'Djibouti', 'Dschibuti', 'Africa', 'Afrika', 'French, Arabic, Somali, Afar', 'Französisch, Arabisch, Somali, Afar', 'fr, ar, so, aa', 'Djibouti', 'DJF', 'French, Arabic, Somali, Afar'),
  ('DK', 'Denmark', 'Dänemark', 'Europe', 'Europa', 'Danish, English, Faroese, German', 'Dänisch, Englisch, Färöisch, Deutsch', 'da, en, fo, de', 'Copenhagen', 'DKK', 'Danish, English, Faroese, German'),
  ('DM', 'Dominica', 'Dominica', 'North America', 'Nordamerika', 'English', 'Englisch', 'en', 'Roseau', 'XCD', 'English'),
  ('DO', 'Dominican Republic', 'Dominikanische Republik', 'North America', 'Nordamerika', 'Spanish', 'Spanisch', 'es', 'Santo Domingo', 'DOP', 'Spanish'),
  ('DZ', 'Algeria', 'Algerien', 'Africa', 'Afrika', 'Arabic', 'Arabisch', 'ar', 'Algiers', 'DZD', 'Arabic'),
  ('EC', 'Ecuador', 'Ecuador', 'South America', 'Südamerika', 'Spanish', 'Spanisch', 'es', 'Quito', 'USD', 'Spanish'),
  ('EE', 'Estonia', 'Estland', 'Europe', 'Europa', 'Estonian, Russian', 'Estnisch, Russisch', 'et, ru', 'Tallinn', 'EUR', 'Estonian, Russian'),
  ('EG', 'Egypt', 'Ägypten', 'Africa', 'Afrika', 'Arabic, English, French', 'Arabisch, Englisch, Französisch', 'ar, en, fr', 'Cairo', 'EGP', 'Arabic, English, French'),
  ('EH', 'Western Sahara', 'Westsahara', 'Africa', 'Afrika', 'Arabic, Hassaniyya', 'Arabisch, Hassaniyya', 'ar, mey', 'El-Aaiun', 'MAD', 'Arabic, Hassaniyya'),
  ('ER', 'Eritrea', 'Eritrea', 'Africa', 'Afrika', 'Afar, Arabic, Tigre, Kunama, Tigrinya', 'Afar, Arabisch, Tigre, Kunama, Tigrinya', 'aa, ar, tig, kun, ti', 'Asmara', 'ERN', 'Afar, Arabic, Tigre, Kunama, Tigrinya'),
  ('ES', 'Spain', 'Spanien', 'Europe', 'Europa', 'Spanish, Catalan, Galician, Basque, Occitan (post 1500)', 'Spanisch, Katalanisch, Galicisch, Baskisch, Okzitanisch', 'es, ca, gl, eu, oc', 'Madrid', 'EUR', 'Spanish, Catalan, Galician, Basque, Occitan (post 1500)'),
  ('ET', 'Ethiopia', 'Äthiopien', 'Africa', 'Afrika', 'Amharic, English, Oromo, Tigrinya, Somali, Sidamo', 'Amharisch, Englisch, Oromo, Tigrinya, Somali, Sidamo', 'am, en, om, ti, so, sid', 'Addis Ababa', 'ETB', 'Amharic, English, Oromo, Tigrinya, Somali, Sidamo'),
  ('FI', 'Finland', 'Finnland', 'Europe', 'Europa', 'Finnish, Swedish, Inari Sami', 'Finnisch, Schwedisch, Inari-Samisch', 'fi, sv, smn', 'Helsinki', 'EUR', 'Finnish, Swedish, Inari Sami'),
  ('FJ', 'Fiji', 'Fidschi', 'Oceania', 'Ozeanien', 'English, Fijian', 'Englisch, Fidschi', 'en, fj', 'Suva', 'FJD', 'English, Fijian'),
  ('FK', 'Falkland Islands', 'Falklandinseln', 'South America', 'Südamerika', 'English', 'Englisch', 'en', 'Stanley', 'FKP', 'English'),
  ('FM', 'Micronesia', 'Mikronesien', 'Oceania', 'Ozeanien', 'English, Chuukese, Pohnpeian, Yapese, Kosraean, Ulithian, Woleaian, Nukuoro, Kapingamarangi', 'Englisch, Chuukesisch, Ponapeanisch, Yapesisch, Kosraeanisch, Ulithian, Woleaian, Nukuoro, Kapingamarangi', 'en, chk, pon, yap, kos, uli, woe, nkr, kpg', 'Palikir', 'USD', 'English, Chuukese, Pohnpeian, Yapese, Kosraean, Ulithian, Woleaian, Nukuoro, Kapingamarangi'),
  ('FO', 'Faroe Islands', 'Färöer', 'Europe', 'Europa', 'Faroese, Danish', 'Färöisch, Dänisch', 'fo, da', 'Torshavn', 'DKK', 'Faroese, Danish'),
  ('FR', 'France', 'Frankreich', 'Europe', 'Europa', 'French, Arpitan, Breton, Corsican, Catalan, Basque, Occitan (post 1500)', 'Französisch, Frankoprovenzalisch, Bretonisch, Korsisch, Katalanisch, Baskisch, Okzitanisch', 'fr, frp, br, co, ca, eu, oc', 'Paris', 'EUR', 'French, Arpitan, Breton, Corsican, Catalan, Basque, Occitan (post 1500)'),
  ('GA', 'Gabon', 'Gabun', 'Africa', 'Afrika', 'French', 'Französisch', 'fr', 'Libreville', 'XAF', 'French'),
  ('GB', 'United Kingdom', 'Vereinigtes Königreich', 'Europe', 'Europa', 'English, Welsh, Scottish Gaelic', 'Englisch, Walisisch, Gälisch (Schottland)', 'en, cy, gd', 'London', 'GBP', 'English, Welsh, Scottish Gaelic'),
  ('GD', 'Grenada', 'Grenada', 'North America', 'Nordamerika', 'English', 'Englisch', 'en', 'St. George''s', 'XCD', 'English'),
  ('GE', 'Georgia', 'Georgien', 'Asia', 'Asien', 'Georgian, Russian, Armenian, Azerbaijani', 'Georgisch, Russisch, Armenisch, Aserbaidschanisch', 'ka, ru, hy, az', 'Tbilisi', 'GEL', 'Georgian, Russian, Armenian, Azerbaijani'),
  ('GF', 'French Guiana', 'Französisch-Guayana', 'South America', 'Südamerika', 'French', 'Französisch', 'fr', 'Cayenne', 'EUR', 'French'),
  ('GG', 'Guernsey', 'Guernsey', 'Europe', 'Europa', 'English, Jèrriais', 'Englisch, Jèrriais', 'en, nrf', 'St Peter Port', 'GBP', 'English, Jèrriais'),
  ('GH', 'Ghana', 'Ghana', 'Africa', 'Afrika', 'English, Akan, Ewe, Twi', 'Englisch, Akan, Ewe, Twi', 'en, ak, ee, tw', 'Accra', 'GHS', 'English, Akan, Ewe, Twi'),
  ('GI', 'Gibraltar', 'Gibraltar', 'Europe', 'Europa', 'English, Spanish, Italian, Portuguese', 'Englisch, Spanisch, Italienisch, Portugiesisch', 'en, es, it, pt', 'Gibraltar', 'GIP', 'English, Spanish, Italian, Portuguese'),
  ('GL', 'Greenland', 'Grönland', 'North America', 'Nordamerika', 'Kalaallisut, Danish, English', 'Grönländisch, Dänisch, Englisch', 'kl, da, en', 'Nuuk', 'DKK', 'Kalaallisut, Danish, English'),
  ('GM', 'Gambia', 'Gambia', 'Africa', 'Afrika', 'English, Mandinka, Gambian Wolof, Wolof, Fulah', 'Englisch, Mandinka, Gambian Wolof, Wolof, Ful', 'en, mnk, wof, wo, ff', 'Banjul', 'GMD', 'English, Mandinka, Gambian Wolof, Wolof, Fulah'),
  ('GN', 'Guinea', 'Guinea', 'Africa', 'Afrika', 'French', 'Französisch', 'fr', 'Conakry', 'GNF', 'French'),
  ('GP', 'Guadeloupe', 'Guadeloupe', 'North America', 'Nordamerika', 'French', 'Französisch', 'fr', 'Basse-Terre', 'EUR', 'French'),
  ('GQ', 'Equatorial Guinea', 'Äquatorialguinea', 'Africa', 'Afrika', 'Spanish, French, Portuguese', 'Spanisch, Französisch, Portugiesisch', 'es, fr, pt', 'Ciudad de la Paz', 'XAF', 'Spanish, French, Portuguese'),
  ('GR', 'Greece', 'Griechenland', 'Europe', 'Europa', 'Modern Greek (1453-), English, French', 'Griechisch, Englisch, Französisch', 'el, en, fr', 'Athens', 'EUR', 'Modern Greek (1453-), English, French'),
  ('GS', 'South Georgia and the South Sandwich Islands', 'Südgeorgien und die Südlichen Sandwichinseln', 'Antarctica', 'Antarktika', 'English', 'Englisch', 'en', 'Grytviken', 'GBP', 'English'),
  ('GT', 'Guatemala', 'Guatemala', 'North America', 'Nordamerika', 'Spanish', 'Spanisch', 'es', 'Guatemala City', 'GTQ', 'Spanish'),
  ('GU', 'Guam', 'Guam', 'Oceania', 'Ozeanien', 'English, Chamorro', 'Englisch, Chamorro', 'en, ch', 'Hagatna', 'USD', 'English, Chamorro'),
  ('GW', 'Guinea-Bissau', 'Guinea-Bissau', 'Africa', 'Afrika', 'Portuguese, Upper Guinea Crioulo', 'Portugiesisch, Upper Guinea Crioulo', 'pt, pov', 'Bissau', 'XOF', 'Portuguese, Upper Guinea Crioulo'),
  ('GY', 'Guyana', 'Guyana', 'South America', 'Südamerika', 'English', 'Englisch', 'en', 'Georgetown', 'GYD', 'English'),
  ('HK', 'Hong Kong', 'Sonderverwaltungsregion Hongkong', 'Asia', 'Asien', 'Chinese, Yue Chinese, English', 'Chinesisch, Kantonesisch, Englisch', 'zh, yue, en', 'Hong Kong', 'HKD', 'Chinese, Yue Chinese, English'),
  ('HM', 'Heard Island and McDonald Islands', 'Heard und McDonaldinseln', 'Antarctica', 'Antarktika', null, null, null, null, 'AUD', null),
  ('HN', 'Honduras', 'Honduras', 'North America', 'Nordamerika', 'Spanish, Garifuna, Mískito', 'Spanisch, Garifuna, Mískito', 'es, cab, miq', 'Tegucigalpa', 'HNL', 'Spanish, Garifuna, Mískito'),
  ('HR', 'Croatia', 'Kroatien', 'Europe', 'Europa', 'Croatian, Serbian', 'Kroatisch, Serbisch', 'hr, sr', 'Zagreb', 'EUR', 'Croatian, Serbian'),
  ('HT', 'Haiti', 'Haiti', 'North America', 'Nordamerika', 'Haitian, French', 'Haiti-Kreolisch, Französisch', 'ht, fr', 'Port-au-Prince', 'HTG', 'Haitian, French'),
  ('HU', 'Hungary', 'Ungarn', 'Europe', 'Europa', 'Hungarian', 'Ungarisch', 'hu', 'Budapest', 'HUF', 'Hungarian'),
  ('ID', 'Indonesia', 'Indonesien', 'Asia', 'Asien', 'Indonesian, English, Dutch, Javanese', 'Indonesisch, Englisch, Niederländisch, Javanisch', 'id, en, nl, jv', 'Jakarta', 'IDR', 'Indonesian, English, Dutch, Javanese'),
  ('IE', 'Ireland', 'Irland', 'Europe', 'Europa', 'English, Irish', 'Englisch, Irisch', 'en, ga', 'Dublin', 'EUR', 'English, Irish'),
  ('IL', 'Israel', 'Israel', 'Asia', 'Asien', 'Hebrew, Arabic, English', 'Hebräisch, Arabisch, Englisch', 'he, ar, en', 'Jerusalem', 'ILS', 'Hebrew, Arabic, English'),
  ('IM', 'Isle of Man', 'Isle of Man', 'Europe', 'Europa', 'English, Manx', 'Englisch, Manx', 'en, gv', 'Douglas', 'GBP', 'English, Manx'),
  ('IN', 'India', 'Indien', 'Asia', 'Asien', 'English, Hindi, Bengali, Telugu, Marathi, Tamil, Urdu, Gujarati, Kannada, Malayalam, Oriya (macrolanguage), Panjabi, Assamese, bh, Santali, Kashmiri, Nepali (macrolanguage), Sindhi, Konkani (macrolanguage), Dogri (macrolanguage), Manipuri, sit, Sanskrit, French, Lushai, inc', 'Englisch, Hindi, Bengalisch, Telugu, Marathi, Tamil, Urdu, Gujarati, Kannada, Malayalam, Oriya, Punjabi, Assamesisch, bh, Santali, Kaschmiri, Nepalesisch, Sindhi, Konkani, Dogri, Meithei, sit, Sanskrit, Französisch, Lushai, inc', 'en, hi, bn, te, mr, ta, ur, gu, kn, ml, or, pa, as, bh, sat, ks, ne, sd, kok, doi, mni, sit, sa, fr, lus, inc', 'New Delhi', 'INR', 'English, Hindi, Bengali, Telugu, Marathi, Tamil, Urdu, Gujarati, Kannada, Malayalam, Oriya (macrolanguage), Panjabi, Assamese, bh, Santali, Kashmiri, Nepali (macrolanguage), Sindhi, Konkani (macrolanguage), Dogri (macrolanguage), Manipuri, sit, Sanskrit, French, Lushai, inc'),
  ('IO', 'British Indian Ocean Territory', 'Britisches Territorium im Indischen Ozean', 'Asia', 'Asien', 'English', 'Englisch', 'en', 'Diego Garcia', 'USD', 'English'),
  ('IQ', 'Iraq', 'Irak', 'Asia', 'Asien', 'Arabic, Kurdish, Armenian', 'Arabisch, Kurdisch, Armenisch', 'ar, ku, hy', 'Baghdad', 'IQD', 'Arabic, Kurdish, Armenian'),
  ('IR', 'Iran', 'Iran', 'Asia', 'Asien', 'Persian, Kurdish', 'Persisch, Kurdisch', 'fa, ku', 'Tehran', 'IRR', 'Persian, Kurdish'),
  ('IS', 'Iceland', 'Island', 'Europe', 'Europa', 'Icelandic, English, German, Danish, Swedish, Norwegian', 'Isländisch, Englisch, Deutsch, Dänisch, Schwedisch, Norwegisch', 'is, en, de, da, sv, no', 'Reykjavik', 'ISK', 'Icelandic, English, German, Danish, Swedish, Norwegian'),
  ('IT', 'Italy', 'Italien', 'Europe', 'Europa', 'Italian, German, French, Sardinian, Catalan, Corsican, Slovenian', 'Italienisch, Deutsch, Französisch, Sardisch, Katalanisch, Korsisch, Slowenisch', 'it, de, fr, sc, ca, co, sl', 'Rome', 'EUR', 'Italian, German, French, Sardinian, Catalan, Corsican, Slovenian'),
  ('JE', 'Jersey', 'Jersey', 'Europe', 'Europa', 'English, French, Jèrriais', 'Englisch, Französisch, Jèrriais', 'en, fr, nrf', 'Saint Helier', 'GBP', 'English, French, Jèrriais'),
  ('JM', 'Jamaica', 'Jamaika', 'North America', 'Nordamerika', 'English', 'Englisch', 'en', 'Kingston', 'JMD', 'English'),
  ('JO', 'Jordan', 'Jordanien', 'Asia', 'Asien', 'Arabic, English', 'Arabisch, Englisch', 'ar, en', 'Amman', 'JOD', 'Arabic, English'),
  ('JP', 'Japan', 'Japan', 'Asia', 'Asien', 'Japanese', 'Japanisch', 'ja', 'Tokyo', 'JPY', 'Japanese'),
  ('KE', 'Kenya', 'Kenia', 'Africa', 'Afrika', 'English, Swahili (macrolanguage)', 'Englisch, Suaheli', 'en, sw', 'Nairobi', 'KES', 'English, Swahili (macrolanguage)'),
  ('KG', 'Kyrgyzstan', 'Kirgisistan', 'Asia', 'Asien', 'Kirghiz, Uzbek, Russian', 'Kirgisisch, Usbekisch, Russisch', 'ky, uz, ru', 'Bishkek', 'KGS', 'Kirghiz, Uzbek, Russian'),
  ('KH', 'Cambodia', 'Kambodscha', 'Asia', 'Asien', 'Khmer, French, English', 'Khmer, Französisch, Englisch', 'km, fr, en', 'Phnom Penh', 'KHR', 'Khmer, French, English'),
  ('KI', 'Kiribati', 'Kiribati', 'Oceania', 'Ozeanien', 'English, Gilbertese', 'Englisch, Kiribatisch', 'en, gil', 'Tarawa', 'AUD', 'English, Gilbertese'),
  ('KM', 'Comoros', 'Komoren', 'Africa', 'Afrika', 'Arabic, French', 'Arabisch, Französisch', 'ar, fr', 'Moroni', 'KMF', 'Arabic, French'),
  ('KN', 'Saint Kitts and Nevis', 'St. Kitts und Nevis', 'North America', 'Nordamerika', 'English', 'Englisch', 'en', 'Basseterre', 'XCD', 'English'),
  ('KP', 'North Korea', 'Nordkorea', 'Asia', 'Asien', 'Korean', 'Koreanisch', 'ko', 'Pyongyang', 'KPW', 'Korean'),
  ('KR', 'South Korea', 'Südkorea', 'Asia', 'Asien', 'Korean, English', 'Koreanisch, Englisch', 'ko, en', 'Seoul', 'KRW', 'Korean, English'),
  ('KW', 'Kuwait', 'Kuwait', 'Asia', 'Asien', 'Arabic, English', 'Arabisch, Englisch', 'ar, en', 'Kuwait City', 'KWD', 'Arabic, English'),
  ('KY', 'Cayman Islands', 'Kaimaninseln', 'North America', 'Nordamerika', 'English', 'Englisch', 'en', 'George Town', 'KYD', 'English'),
  ('KZ', 'Kazakhstan', 'Kasachstan', 'Asia', 'Asien', 'Kazakh, Russian', 'Kasachisch, Russisch', 'kk, ru', 'Nur-Sultan', 'KZT', 'Kazakh, Russian'),
  ('LA', 'Laos', 'Laos', 'Asia', 'Asien', 'Lao, French, English', 'Laotisch, Französisch, Englisch', 'lo, fr, en', 'Vientiane', 'LAK', 'Lao, French, English'),
  ('LB', 'Lebanon', 'Libanon', 'Asia', 'Asien', 'Arabic, French, English, Armenian', 'Arabisch, Französisch, Englisch, Armenisch', 'ar, fr, en, hy', 'Beirut', 'LBP', 'Arabic, French, English, Armenian'),
  ('LC', 'Saint Lucia', 'St. Lucia', 'North America', 'Nordamerika', 'English', 'Englisch', 'en', 'Castries', 'XCD', 'English'),
  ('LI', 'Liechtenstein', 'Liechtenstein', 'Europe', 'Europa', 'German', 'Deutsch', 'de', 'Vaduz', 'CHF', 'German'),
  ('LK', 'Sri Lanka', 'Sri Lanka', 'Asia', 'Asien', 'Sinhala, Tamil, English', 'Singhalesisch, Tamil, Englisch', 'si, ta, en', 'Colombo', 'LKR', 'Sinhala, Tamil, English'),
  ('LR', 'Liberia', 'Liberia', 'Africa', 'Afrika', 'English', 'Englisch', 'en', 'Monrovia', 'LRD', 'English'),
  ('LS', 'Lesotho', 'Lesotho', 'Africa', 'Afrika', 'English, Southern Sotho, Zulu, Xhosa', 'Englisch, Süd-Sotho, Zulu, Xhosa', 'en, st, zu, xh', 'Maseru', 'LSL', 'English, Southern Sotho, Zulu, Xhosa'),
  ('LT', 'Lithuania', 'Litauen', 'Europe', 'Europa', 'Lithuanian, Russian, Polish', 'Litauisch, Russisch, Polnisch', 'lt, ru, pl', 'Vilnius', 'EUR', 'Lithuanian, Russian, Polish'),
  ('LU', 'Luxembourg', 'Luxemburg', 'Europe', 'Europa', 'Luxembourgish, German, French', 'Luxemburgisch, Deutsch, Französisch', 'lb, de, fr', 'Luxembourg', 'EUR', 'Luxembourgish, German, French'),
  ('LV', 'Latvia', 'Lettland', 'Europe', 'Europa', 'Latvian, Russian, Lithuanian', 'Lettisch, Russisch, Litauisch', 'lv, ru, lt', 'Riga', 'EUR', 'Latvian, Russian, Lithuanian'),
  ('LY', 'Libya', 'Libyen', 'Africa', 'Afrika', 'Arabic, Italian, English', 'Arabisch, Italienisch, Englisch', 'ar, it, en', 'Tripoli', 'LYD', 'Arabic, Italian, English'),
  ('MA', 'Morocco', 'Marokko', 'Africa', 'Afrika', 'Arabic, ber, French', 'Arabisch, ber, Französisch', 'ar, ber, fr', 'Rabat', 'MAD', 'Arabic, ber, French'),
  ('MC', 'Monaco', 'Monaco', 'Europe', 'Europa', 'French, English, Italian', 'Französisch, Englisch, Italienisch', 'fr, en, it', 'Monaco', 'EUR', 'French, English, Italian'),
  ('MD', 'Moldova', 'Republik Moldau', 'Europe', 'Europa', 'Romanian, Russian, Gagauz, Turkish', 'Rumänisch, Russisch, Gagausisch, Türkisch', 'ro, ru, gag, tr', 'Chisinau', 'MDL', 'Romanian, Russian, Gagauz, Turkish'),
  ('ME', 'Montenegro', 'Montenegro', 'Europe', 'Europa', 'Serbian, Hungarian, Bosnian, Albanian, Croatian, Romany', 'Serbisch, Ungarisch, Bosnisch, Albanisch, Kroatisch, Romani', 'sr, hu, bs, sq, hr, rom', 'Podgorica', 'EUR', 'Serbian, Hungarian, Bosnian, Albanian, Croatian, Romany'),
  ('MF', 'Saint Martin', 'St. Martin', 'North America', 'Nordamerika', 'French', 'Französisch', 'fr', 'Marigot', 'EUR', 'French'),
  ('MG', 'Madagascar', 'Madagaskar', 'Africa', 'Afrika', 'French, Malagasy', 'Französisch, Malagasy', 'fr, mg', 'Antananarivo', 'MGA', 'French, Malagasy'),
  ('MH', 'Marshall Islands', 'Marshallinseln', 'Oceania', 'Ozeanien', 'Marshallese, English', 'Marschallesisch, Englisch', 'mh, en', 'Majuro', 'USD', 'Marshallese, English'),
  ('MK', 'North Macedonia', 'Nordmazedonien', 'Europe', 'Europa', 'Macedonian, Albanian, Turkish, Roma, Serbian', 'Mazedonisch, Albanisch, Türkisch, Roma, Serbisch', 'mk, sq, tr, rmm, sr', 'Skopje', 'MKD', 'Macedonian, Albanian, Turkish, Roma, Serbian'),
  ('ML', 'Mali', 'Mali', 'Africa', 'Afrika', 'French, Bambara', 'Französisch, Bambara', 'fr, bm', 'Bamako', 'XOF', 'French, Bambara'),
  ('MM', 'Myanmar', 'Myanmar', 'Asia', 'Asien', 'Burmese', 'Birmanisch', 'my', 'Nay Pyi Taw', 'MMK', 'Burmese'),
  ('MN', 'Mongolia', 'Mongolei', 'Asia', 'Asien', 'Mongolian, Russian', 'Mongolisch, Russisch', 'mn, ru', 'Ulaanbaatar', 'MNT', 'Mongolian, Russian'),
  ('MO', 'Macao', 'Sonderverwaltungsregion Macau', 'Asia', 'Asien', 'Chinese, Portuguese', 'Chinesisch, Portugiesisch', 'zh, pt', 'Macao', 'MOP', 'Chinese, Portuguese'),
  ('MP', 'Northern Mariana Islands', 'Nördliche Marianen', 'Oceania', 'Ozeanien', 'Filipino, Tagalog, Chinese, Chamorro, English', 'Filipino, Tagalog, Chinesisch, Chamorro, Englisch', 'fil, tl, zh, ch, en', 'Saipan', 'USD', 'Filipino, Tagalog, Chinese, Chamorro, English'),
  ('MQ', 'Martinique', 'Martinique', 'North America', 'Nordamerika', 'French', 'Französisch', 'fr', 'Fort-de-France', 'EUR', 'French'),
  ('MR', 'Mauritania', 'Mauretanien', 'Africa', 'Afrika', 'Arabic, Pulaar, Soninke, French, Hassaniyya, Wolof', 'Arabisch, Pulaar, Soninke, Französisch, Hassaniyya, Wolof', 'ar, fuc, snk, fr, mey, wo', 'Nouakchott', 'MRU', 'Arabic, Pulaar, Soninke, French, Hassaniyya, Wolof'),
  ('MS', 'Montserrat', 'Montserrat', 'North America', 'Nordamerika', 'English', 'Englisch', 'en', 'Plymouth', 'XCD', 'English'),
  ('MT', 'Malta', 'Malta', 'Europe', 'Europa', 'Maltese, English', 'Maltesisch, Englisch', 'mt, en', 'Valletta', 'EUR', 'Maltese, English'),
  ('MU', 'Mauritius', 'Mauritius', 'Africa', 'Afrika', 'English, Bhojpuri, French', 'Englisch, Bhodschpuri, Französisch', 'en, bho, fr', 'Port Louis', 'MUR', 'English, Bhojpuri, French'),
  ('MV', 'Maldives', 'Malediven', 'Asia', 'Asien', 'Dhivehi, English', 'Dhivehi, Englisch', 'dv, en', 'Male', 'MVR', 'Dhivehi, English'),
  ('MW', 'Malawi', 'Malawi', 'Africa', 'Afrika', 'Nyanja, Yao, Tumbuka, Malawi Sena', 'Nyanja, Yao, Tumbuka, Malawi Sena', 'ny, yao, tum, swk', 'Lilongwe', 'MWK', 'Nyanja, Yao, Tumbuka, Malawi Sena'),
  ('MX', 'Mexico', 'Mexiko', 'North America', 'Nordamerika', 'Spanish', 'Spanisch', 'es', 'Mexico City', 'MXN', 'Spanish'),
  ('MY', 'Malaysia', 'Malaysia', 'Asia', 'Asien', 'Malay (macrolanguage), English, Chinese, Tamil, Telugu, Malayalam, Panjabi, Thai', 'Malaiisch, Englisch, Chinesisch, Tamil, Telugu, Malayalam, Punjabi, Thailändisch', 'ms, en, zh, ta, te, ml, pa, th', 'Kuala Lumpur', 'MYR', 'Malay (macrolanguage), English, Chinese, Tamil, Telugu, Malayalam, Panjabi, Thai'),
  ('MZ', 'Mozambique', 'Mosambik', 'Africa', 'Afrika', 'Portuguese, Makhuwa', 'Portugiesisch, Makua', 'pt, vmw', 'Maputo', 'MZN', 'Portuguese, Makhuwa'),
  ('NA', 'Namibia', 'Namibia', 'Africa', 'Afrika', 'English, Afrikaans, German, Herero, Khoekhoe', 'Englisch, Afrikaans, Deutsch, Herero, Nama', 'en, af, de, hz, naq', 'Windhoek', 'NAD', 'English, Afrikaans, German, Herero, Khoekhoe'),
  ('NC', 'New Caledonia', 'Neukaledonien', 'Oceania', 'Ozeanien', 'French', 'Französisch', 'fr', 'Noumea', 'XPF', 'French'),
  ('NE', 'Niger', 'Niger', 'Africa', 'Afrika', 'French, Hausa, Kanuri, Zarma', 'Französisch, Haussa, Kanuri, Zarma', 'fr, ha, kr, dje', 'Niamey', 'XOF', 'French, Hausa, Kanuri, Zarma'),
  ('NF', 'Norfolk Island', 'Norfolkinsel', 'Oceania', 'Ozeanien', 'English', 'Englisch', 'en', 'Kingston', 'AUD', 'English'),
  ('NG', 'Nigeria', 'Nigeria', 'Africa', 'Afrika', 'English, Hausa, Yoruba, Igbo, Fulah', 'Englisch, Haussa, Yoruba, Igbo, Ful', 'en, ha, yo, ig, ff', 'Abuja', 'NGN', 'English, Hausa, Yoruba, Igbo, Fulah'),
  ('NI', 'Nicaragua', 'Nicaragua', 'North America', 'Nordamerika', 'Spanish, English', 'Spanisch, Englisch', 'es, en', 'Managua', 'NIO', 'Spanish, English'),
  ('NL', 'The Netherlands', 'Niederlande', 'Europe', 'Europa', 'Dutch, Western Frisian', 'Niederländisch, Westfriesisch', 'nl, fy', 'Amsterdam', 'EUR', 'Dutch, Western Frisian'),
  ('NO', 'Norway', 'Norwegen', 'Europe', 'Europa', 'Norwegian, Norwegian Bokmål, Norwegian Nynorsk, Northern Sami, Finnish', 'Norwegisch, Norwegisch (Bokmål), Norwegisch (Nynorsk), Nordsamisch, Finnisch', 'no, nb, nn, se, fi', 'Oslo', 'NOK', 'Norwegian, Norwegian Bokmål, Norwegian Nynorsk, Northern Sami, Finnish'),
  ('NP', 'Nepal', 'Nepal', 'Asia', 'Asien', 'Nepali (macrolanguage), English', 'Nepalesisch, Englisch', 'ne, en', 'Kathmandu', 'NPR', 'Nepali (macrolanguage), English'),
  ('NR', 'Nauru', 'Nauru', 'Oceania', 'Ozeanien', 'Nauru, English', 'Nauruisch, Englisch', 'na, en', 'Yaren', 'AUD', 'Nauru, English'),
  ('NU', 'Niue', 'Niue', 'Oceania', 'Ozeanien', 'Niuean, English', 'Niue, Englisch', 'niu, en', 'Alofi', 'NZD', 'Niuean, English'),
  ('NZ', 'New Zealand', 'Neuseeland', 'Oceania', 'Ozeanien', 'English, Maori', 'Englisch, Māori', 'en, mi', 'Wellington', 'NZD', 'English, Maori'),
  ('OM', 'Oman', 'Oman', 'Asia', 'Asien', 'Arabic, English, Baluchi, Urdu', 'Arabisch, Englisch, Belutschisch, Urdu', 'ar, en, bal, ur', 'Muscat', 'OMR', 'Arabic, English, Baluchi, Urdu'),
  ('PA', 'Panama', 'Panama', 'North America', 'Nordamerika', 'Spanish, English', 'Spanisch, Englisch', 'es, en', 'Panama City', 'PAB', 'Spanish, English'),
  ('PE', 'Peru', 'Peru', 'South America', 'Südamerika', 'Spanish, Quechua, Aymara', 'Spanisch, Quechua, Aymara', 'es, qu, ay', 'Lima', 'PEN', 'Spanish, Quechua, Aymara'),
  ('PF', 'French Polynesia', 'Französisch-Polynesien', 'Oceania', 'Ozeanien', 'French, Tahitian', 'Französisch, Tahitisch', 'fr, ty', 'Papeete', 'XPF', 'French, Tahitian'),
  ('PG', 'Papua New Guinea', 'Papua-Neuguinea', 'Oceania', 'Ozeanien', 'English, Hiri Motu, Motu, Tok Pisin', 'Englisch, Hiri-Motu, Motu, Neumelanesisch', 'en, ho, meu, tpi', 'Port Moresby', 'PGK', 'English, Hiri Motu, Motu, Tok Pisin'),
  ('PH', 'Philippines', 'Philippinen', 'Asia', 'Asien', 'Tagalog, English, Filipino, Cebuano, Iloko, Hiligaynon, Waray (Philippines), Pampanga, Bikol, Central Bikol, Pangasinan, Maranao, Tausug, Maguindanaon, Chavacano, Kinaray-A, Surigaonon, Masbatenyo, Aklanon, Ibanag, Yakan, Cotabato Manobo, Inabaknon', 'Tagalog, Englisch, Filipino, Cebuano, Ilokano, Hiligaynon, Waray, Pampanggan, Bikol, Central Bikol, Pangasinan, Maranao, Tausug, Maguindanaon, Chavacano, Kinaray-a, Surigaonon, Masbatenyo, Aklanon, Ibanag, Yakan, Cotabato Manobo, Inabaknon', 'tl, en, fil, ceb, ilo, hil, war, pam, bik, bcl, pag, mrw, tsg, mdh, cbk, krj, sgd, msb, akl, ibg, yka, mta, abx', 'Manila', 'PHP', 'Tagalog, English, Filipino, Cebuano, Iloko, Hiligaynon, Waray (Philippines), Pampanga, Bikol, Central Bikol, Pangasinan, Maranao, Tausug, Maguindanaon, Chavacano, Kinaray-A, Surigaonon, Masbatenyo, Aklanon, Ibanag, Yakan, Cotabato Manobo, Inabaknon'),
  ('PK', 'Pakistan', 'Pakistan', 'Asia', 'Asien', 'Urdu, English, Panjabi, Sindhi, Pushto, Brahui', 'Urdu, Englisch, Punjabi, Sindhi, Paschtu, Brahui', 'ur, en, pa, sd, ps, brh', 'Islamabad', 'PKR', 'Urdu, English, Panjabi, Sindhi, Pushto, Brahui'),
  ('PL', 'Poland', 'Polen', 'Europe', 'Europa', 'Polish', 'Polnisch', 'pl', 'Warsaw', 'PLN', 'Polish'),
  ('PM', 'Saint Pierre and Miquelon', 'St. Pierre und Miquelon', 'North America', 'Nordamerika', 'French', 'Französisch', 'fr', 'Saint-Pierre', 'EUR', 'French'),
  ('PN', 'Pitcairn', 'Pitcairninseln', 'Oceania', 'Ozeanien', 'English', 'Englisch', 'en', 'Adamstown', 'NZD', 'English'),
  ('PR', 'Puerto Rico', 'Puerto Rico', 'North America', 'Nordamerika', 'English, Spanish', 'Englisch, Spanisch', 'en, es', 'San Juan', 'USD', 'English, Spanish'),
  ('PS', 'Palestinian Territory', 'Palästinensische Autonomiegebiete', 'Asia', 'Asien', 'Arabic', 'Arabisch', 'ar', 'East Jerusalem', 'ILS', 'Arabic'),
  ('PT', 'Portugal', 'Portugal', 'Europe', 'Europa', 'Portuguese, Mirandese', 'Portugiesisch, Mirandesisch', 'pt, mwl', 'Lisbon', 'EUR', 'Portuguese, Mirandese'),
  ('PW', 'Palau', 'Palau', 'Oceania', 'Ozeanien', 'Palauan, Sonsorol, English, Tobian, Japanese, Filipino, Chinese', 'Palau, Sonsorol, Englisch, Tobian, Japanisch, Filipino, Chinesisch', 'pau, sov, en, tox, ja, fil, zh', 'Melekeok', 'USD', 'Palauan, Sonsorol, English, Tobian, Japanese, Filipino, Chinese'),
  ('PY', 'Paraguay', 'Paraguay', 'South America', 'Südamerika', 'Spanish, Guarani', 'Spanisch, Guaraní', 'es, gn', 'Asuncion', 'PYG', 'Spanish, Guarani'),
  ('QA', 'Qatar', 'Katar', 'Asia', 'Asien', 'Arabic, Spanish', 'Arabisch, Spanisch', 'ar, es', 'Doha', 'QAR', 'Arabic, Spanish'),
  ('RE', 'Reunion', 'Réunion', 'Africa', 'Afrika', 'French', 'Französisch', 'fr', 'Saint-Denis', 'EUR', 'French'),
  ('RO', 'Romania', 'Rumänien', 'Europe', 'Europa', 'Romanian, Hungarian, Romany', 'Rumänisch, Ungarisch, Romani', 'ro, hu, rom', 'Bucharest', 'RON', 'Romanian, Hungarian, Romany'),
  ('RS', 'Serbia', 'Serbien', 'Europe', 'Europa', 'Serbian, Hungarian, Bosnian, Romany', 'Serbisch, Ungarisch, Bosnisch, Romani', 'sr, hu, bs, rom', 'Belgrade', 'RSD', 'Serbian, Hungarian, Bosnian, Romany'),
  ('RU', 'Russia', 'Russland', 'Europe', 'Europa', 'Russian, Tatar, Kalmyk, cau, Adyghe, Komi, Chechen, Tuvinian, Chuvash, Udmurt, tut, Mansi, Buriat, Erzya, Moksha, Mari (Russia), Bashkir, Ingush, Kabardian, Karachay-Balkar, Avaric, Yakut, Nogai', 'Russisch, Tatarisch, Kalmückisch, cau, Adygeisch, Komi, Tschetschenisch, Tuwinisch, Tschuwaschisch, Udmurtisch, tut, Mansi, Burjatisch, Ersja-Mordwinisch, Mokschanisch, Mari, Baschkirisch, Inguschisch, Kabardinisch, Karatschaiisch-Balkarisch, Awarisch, Jakutisch, Nogai', 'ru, tt, xal, cau, ady, kv, ce, tyv, cv, udm, tut, mns, bua, myv, mdf, chm, ba, inh, kbd, krc, av, sah, nog', 'Moscow', 'RUB', 'Russian, Tatar, Kalmyk, cau, Adyghe, Komi, Chechen, Tuvinian, Chuvash, Udmurt, tut, Mansi, Buriat, Erzya, Moksha, Mari (Russia), Bashkir, Ingush, Kabardian, Karachay-Balkar, Avaric, Yakut, Nogai'),
  ('RW', 'Rwanda', 'Ruanda', 'Africa', 'Afrika', 'Kinyarwanda, English, French, Swahili (macrolanguage)', 'Kinyarwanda, Englisch, Französisch, Suaheli', 'rw, en, fr, sw', 'Kigali', 'RWF', 'Kinyarwanda, English, French, Swahili (macrolanguage)'),
  ('SA', 'Saudi Arabia', 'Saudi-Arabien', 'Asia', 'Asien', 'Arabic', 'Arabisch', 'ar', 'Riyadh', 'SAR', 'Arabic'),
  ('SB', 'Solomon Islands', 'Salomonen', 'Oceania', 'Ozeanien', 'English, Tok Pisin', 'Englisch, Neumelanesisch', 'en, tpi', 'Honiara', 'SBD', 'English, Tok Pisin'),
  ('SC', 'Seychelles', 'Seychellen', 'Africa', 'Afrika', 'English, French', 'Englisch, Französisch', 'en, fr', 'Victoria', 'SCR', 'English, French'),
  ('SD', 'Sudan', 'Sudan', 'Africa', 'Afrika', 'Arabic, English, Nobiin', 'Arabisch, Englisch, Nobiin', 'ar, en, fia', 'Khartoum', 'SDG', 'Arabic, English, Nobiin'),
  ('SE', 'Sweden', 'Schweden', 'Europe', 'Europa', 'Swedish, Northern Sami, Southern Sami, Finnish', 'Schwedisch, Nordsamisch, Südsamisch, Finnisch', 'sv, se, sma, fi', 'Stockholm', 'SEK', 'Swedish, Northern Sami, Southern Sami, Finnish'),
  ('SG', 'Singapore', 'Singapur', 'Asia', 'Asien', 'Mandarin Chinese, English, Malay (macrolanguage), Tamil, Chinese', 'Mandarin Chinese, Englisch, Malaiisch, Tamil, Chinesisch', 'cmn, en, ms, ta, zh', 'Singapore', 'SGD', 'Mandarin Chinese, English, Malay (macrolanguage), Tamil, Chinese'),
  ('SH', 'Saint Helena', 'St. Helena', 'Africa', 'Afrika', 'English', 'Englisch', 'en', 'Jamestown', 'SHP', 'English'),
  ('SI', 'Slovenia', 'Slowenien', 'Europe', 'Europa', 'Slovenian, Serbo-Croatian', 'Slowenisch, Serbo-Kroatisch', 'sl, sh', 'Ljubljana', 'EUR', 'Slovenian, Serbo-Croatian'),
  ('SJ', 'Svalbard and Jan Mayen', 'Spitzbergen und Jan Mayen', 'Europe', 'Europa', 'Norwegian, Russian', 'Norwegisch, Russisch', 'no, ru', 'Longyearbyen', 'NOK', 'Norwegian, Russian'),
  ('SK', 'Slovakia', 'Slowakei', 'Europe', 'Europa', 'Slovak, Hungarian', 'Slowakisch, Ungarisch', 'sk, hu', 'Bratislava', 'EUR', 'Slovak, Hungarian'),
  ('SL', 'Sierra Leone', 'Sierra Leone', 'Africa', 'Afrika', 'English, Mende (Sierra Leone), Timne', 'Englisch, Mende, Temne', 'en, men, tem', 'Freetown', 'SLE', 'English, Mende (Sierra Leone), Timne'),
  ('SM', 'San Marino', 'San Marino', 'Europe', 'Europa', 'Italian', 'Italienisch', 'it', 'San Marino', 'EUR', 'Italian'),
  ('SN', 'Senegal', 'Senegal', 'Africa', 'Afrika', 'French, Wolof, Pulaar, Mandinka', 'Französisch, Wolof, Pulaar, Mandinka', 'fr, wo, fuc, mnk', 'Dakar', 'XOF', 'French, Wolof, Pulaar, Mandinka'),
  ('SO', 'Somalia', 'Somalia', 'Africa', 'Afrika', 'Somali, Arabic, Italian, English', 'Somali, Arabisch, Italienisch, Englisch', 'so, ar, it, en', 'Mogadishu', 'SOS', 'Somali, Arabic, Italian, English'),
  ('SR', 'Suriname', 'Suriname', 'South America', 'Südamerika', 'Dutch, English, Sranan Tongo, Caribbean Hindustani, Javanese', 'Niederländisch, Englisch, Srananisch, Caribbean Hindustani, Javanisch', 'nl, en, srn, hns, jv', 'Paramaribo', 'SRD', 'Dutch, English, Sranan Tongo, Caribbean Hindustani, Javanese'),
  ('SS', 'South Sudan', 'Südsudan', 'Africa', 'Afrika', 'English', 'Englisch', 'en', 'Juba', 'SSP', 'English'),
  ('ST', 'Sao Tome and Principe', 'São Tomé und Príncipe', 'Africa', 'Afrika', 'Portuguese', 'Portugiesisch', 'pt', 'Sao Tome', 'STN', 'Portuguese'),
  ('SV', 'El Salvador', 'El Salvador', 'North America', 'Nordamerika', 'Spanish', 'Spanisch', 'es', 'San Salvador', 'USD', 'Spanish'),
  ('SX', 'Sint Maarten', 'Sint Maarten', 'North America', 'Nordamerika', 'Dutch, English', 'Niederländisch, Englisch', 'nl, en', 'Philipsburg', 'XCG', 'Dutch, English'),
  ('SY', 'Syria', 'Syrien', 'Asia', 'Asien', 'Arabic, Kurdish, Armenian, Official Aramaic (700-300 BCE), French, English', 'Arabisch, Kurdisch, Armenisch, Aramäisch, Französisch, Englisch', 'ar, ku, hy, arc, fr, en', 'Damascus', 'SYP', 'Arabic, Kurdish, Armenian, Official Aramaic (700-300 BCE), French, English'),
  ('SZ', 'Eswatini', 'Eswatini', 'Africa', 'Afrika', 'English, Swati', 'Englisch, Swazi', 'en, ss', 'Mbabane', 'SZL', 'English, Swati'),
  ('TC', 'Turks and Caicos Islands', 'Turks- und Caicosinseln', 'North America', 'Nordamerika', 'English', 'Englisch', 'en', 'Cockburn Town', 'USD', 'English'),
  ('TD', 'Chad', 'Tschad', 'Africa', 'Afrika', 'French, Arabic, Sara', 'Französisch, Arabisch, Sara', 'fr, ar, sre', 'N''Djamena', 'XAF', 'French, Arabic, Sara'),
  ('TF', 'French Southern Territories', 'Französische Süd- und Antarktisgebiete', 'Antarctica', 'Antarktika', 'French', 'Französisch', 'fr', 'Port-aux-Francais', 'EUR', 'French'),
  ('TG', 'Togo', 'Togo', 'Africa', 'Afrika', 'French, Ewe, Mina (Cameroon), Kabiyè, Dagbani, Hausa', 'Französisch, Ewe, Mina (Cameroon), Kabiyè, Dagbani, Haussa', 'fr, ee, hna, kbp, dag, ha', 'Lome', 'XOF', 'French, Ewe, Mina (Cameroon), Kabiyè, Dagbani, Hausa'),
  ('TH', 'Thailand', 'Thailand', 'Asia', 'Asien', 'Thai, English', 'Thailändisch, Englisch', 'th, en', 'Bangkok', 'THB', 'Thai, English'),
  ('TJ', 'Tajikistan', 'Tadschikistan', 'Asia', 'Asien', 'Tajik, Russian', 'Tadschikisch, Russisch', 'tg, ru', 'Dushanbe', 'TJS', 'Tajik, Russian'),
  ('TK', 'Tokelau', 'Tokelau', 'Oceania', 'Ozeanien', 'Tokelau, English', 'Tokelauanisch, Englisch', 'tkl, en', null, 'NZD', 'Tokelau, English'),
  ('TL', 'Timor Leste', 'Timor-Leste', 'Oceania', 'Ozeanien', 'Tetum, Portuguese, Indonesian, English', 'Tetum, Portugiesisch, Indonesisch, Englisch', 'tet, pt, id, en', 'Dili', 'USD', 'Tetum, Portuguese, Indonesian, English'),
  ('TM', 'Turkmenistan', 'Turkmenistan', 'Asia', 'Asien', 'Turkmen, Russian, Uzbek', 'Turkmenisch, Russisch, Usbekisch', 'tk, ru, uz', 'Ashgabat', 'TMT', 'Turkmen, Russian, Uzbek'),
  ('TN', 'Tunisia', 'Tunesien', 'Africa', 'Afrika', 'Arabic, French', 'Arabisch, Französisch', 'ar, fr', 'Tunis', 'TND', 'Arabic, French'),
  ('TO', 'Tonga', 'Tonga', 'Oceania', 'Ozeanien', 'Tonga (Tonga Islands), English', 'Tongaisch, Englisch', 'to, en', 'Nuku''alofa', 'TOP', 'Tonga (Tonga Islands), English'),
  ('TR', 'Turkey', 'Türkei', 'Asia', 'Asien', 'Turkish, Kurdish, Dimli (individual language), Azerbaijani, Avaric', 'Türkisch, Kurdisch, Dimli (individual language), Aserbaidschanisch, Awarisch', 'tr, ku, diq, az, av', 'Ankara', 'TRY', 'Turkish, Kurdish, Dimli (individual language), Azerbaijani, Avaric'),
  ('TT', 'Trinidad and Tobago', 'Trinidad und Tobago', 'North America', 'Nordamerika', 'English, Caribbean Hindustani, French, Spanish, Chinese', 'Englisch, Caribbean Hindustani, Französisch, Spanisch, Chinesisch', 'en, hns, fr, es, zh', 'Port of Spain', 'TTD', 'English, Caribbean Hindustani, French, Spanish, Chinese'),
  ('TV', 'Tuvalu', 'Tuvalu', 'Oceania', 'Ozeanien', 'Tuvalu, English, Samoan, Gilbertese', 'Tuvaluisch, Englisch, Samoanisch, Kiribatisch', 'tvl, en, sm, gil', 'Funafuti', 'AUD', 'Tuvalu, English, Samoan, Gilbertese'),
  ('TW', 'Taiwan', 'Taiwan', 'Asia', 'Asien', 'Chinese, Min Nan Chinese, Hakka Chinese', 'Chinesisch, Min Nan, Hakka', 'zh, nan, hak', 'Taipei', 'TWD', 'Chinese, Min Nan Chinese, Hakka Chinese'),
  ('TZ', 'Tanzania', 'Tansania', 'Africa', 'Afrika', 'Swahili (macrolanguage), English, Arabic', 'Suaheli, Englisch, Arabisch', 'sw, en, ar', 'Dodoma', 'TZS', 'Swahili (macrolanguage), English, Arabic'),
  ('UA', 'Ukraine', 'Ukraine', 'Europe', 'Europa', 'Ukrainian, Russian, Romany, Polish, Hungarian', 'Ukrainisch, Russisch, Romani, Polnisch, Ungarisch', 'uk, ru, rom, pl, hu', 'Kyiv', 'UAH', 'Ukrainian, Russian, Romany, Polish, Hungarian'),
  ('UG', 'Uganda', 'Uganda', 'Africa', 'Afrika', 'English, Ganda, Swahili (macrolanguage), Arabic', 'Englisch, Ganda, Suaheli, Arabisch', 'en, lg, sw, ar', 'Kampala', 'UGX', 'English, Ganda, Swahili (macrolanguage), Arabic'),
  ('UM', 'United States Minor Outlying Islands', 'Amerikanische Überseeinseln', 'Oceania', 'Ozeanien', 'English', 'Englisch', 'en', null, 'USD', 'English'),
  ('US', 'United States', 'Vereinigte Staaten', 'North America', 'Nordamerika', 'English, Spanish, Hawaiian, French', 'Englisch, Spanisch, Hawaiisch, Französisch', 'en, es, haw, fr', 'Washington', 'USD', 'English, Spanish, Hawaiian, French'),
  ('UY', 'Uruguay', 'Uruguay', 'South America', 'Südamerika', 'Spanish', 'Spanisch', 'es', 'Montevideo', 'UYU', 'Spanish'),
  ('UZ', 'Uzbekistan', 'Usbekistan', 'Asia', 'Asien', 'Uzbek, Russian, Tajik', 'Usbekisch, Russisch, Tadschikisch', 'uz, ru, tg', 'Tashkent', 'UZS', 'Uzbek, Russian, Tajik'),
  ('VA', 'Vatican', 'Vatikanstadt', 'Europe', 'Europa', 'Latin, Italian, French', 'Latein, Italienisch, Französisch', 'la, it, fr', 'Vatican City', 'EUR', 'Latin, Italian, French'),
  ('VC', 'Saint Vincent and the Grenadines', 'St. Vincent und die Grenadinen', 'North America', 'Nordamerika', 'English, French', 'Englisch, Französisch', 'en, fr', 'Kingstown', 'XCD', 'English, French'),
  ('VE', 'Venezuela', 'Venezuela', 'South America', 'Südamerika', 'Spanish', 'Spanisch', 'es', 'Caracas', 'VES', 'Spanish'),
  ('VG', 'British Virgin Islands', 'Britische Jungferninseln', 'North America', 'Nordamerika', 'English', 'Englisch', 'en', 'Road Town', 'USD', 'English'),
  ('VI', 'U.S. Virgin Islands', 'Amerikanische Jungferninseln', 'North America', 'Nordamerika', 'English', 'Englisch', 'en', 'Charlotte Amalie', 'USD', 'English'),
  ('VN', 'Vietnam', 'Vietnam', 'Asia', 'Asien', 'Vietnamese, English, French, Chinese, Khmer', 'Vietnamesisch, Englisch, Französisch, Chinesisch, Khmer', 'vi, en, fr, zh, km', 'Hanoi', 'VND', 'Vietnamese, English, French, Chinese, Khmer'),
  ('VU', 'Vanuatu', 'Vanuatu', 'Oceania', 'Ozeanien', 'Bislama, English, French', 'Bislama, Englisch, Französisch', 'bi, en, fr', 'Port Vila', 'VUV', 'Bislama, English, French'),
  ('WF', 'Wallis and Futuna', 'Wallis und Futuna', 'Oceania', 'Ozeanien', 'Wallisian, East Futuna, French', 'Wallisian, East Futuna, Französisch', 'wls, fud, fr', 'Mata Utu', 'XPF', 'Wallisian, East Futuna, French'),
  ('WS', 'Samoa', 'Samoa', 'Oceania', 'Ozeanien', 'Samoan, English', 'Samoanisch, Englisch', 'sm, en', 'Apia', 'WST', 'Samoan, English'),
  ('YE', 'Yemen', 'Jemen', 'Asia', 'Asien', 'Arabic', 'Arabisch', 'ar', 'Sanaa', 'YER', 'Arabic'),
  ('YT', 'Mayotte', 'Mayotte', 'Africa', 'Afrika', 'French', 'Französisch', 'fr', 'Mamoudzou', 'EUR', 'French'),
  ('ZA', 'South Africa', 'Südafrika', 'Africa', 'Afrika', 'Zulu, Xhosa, Afrikaans, Pedi, English, Tswana, Southern Sotho, Tsonga, Swati, Venda, South Ndebele', 'Zulu, Xhosa, Afrikaans, Nord-Sotho, Englisch, Tswana, Süd-Sotho, Tsonga, Swazi, Venda, Süd-Ndebele', 'zu, xh, af, nso, en, tn, st, ts, ss, ve, nr', 'Pretoria', 'ZAR', 'Zulu, Xhosa, Afrikaans, Pedi, English, Tswana, Southern Sotho, Tsonga, Swati, Venda, South Ndebele'),
  ('ZM', 'Zambia', 'Sambia', 'Africa', 'Afrika', 'English, Bemba (Zambia), Lozi, Lunda, Luvale, Nyanja, Tonga (Zambia)', 'Englisch, Bemba, Lozi, Lunda, Luvale, Nyanja, Tonga (Zambia)', 'en, bem, loz, lun, lue, ny, toi', 'Lusaka', 'ZMW', 'English, Bemba (Zambia), Lozi, Lunda, Luvale, Nyanja, Tonga (Zambia)'),
  ('ZW', 'Zimbabwe', 'Simbabwe', 'Africa', 'Afrika', 'English, Shona, South Ndebele, North Ndebele', 'Englisch, Shona, Süd-Ndebele, Nord-Ndebele', 'en, sn, nr, nd', 'Harare', 'ZWG', 'English, Shona, South Ndebele, North Ndebele')
on conflict (iso2) do nothing;

-- To refresh already-seeded rows instead of skipping them, replace the line above with:
-- on conflict (iso2) do update set
--   country_en = excluded.country_en, country_de = excluded.country_de,
--   continent_en = excluded.continent_en, continent_de = excluded.continent_de,
--   languages_en = excluded.languages_en, languages_de = excluded.languages_de,
--   language_codes = excluded.language_codes, capital = excluded.capital,
--   currency = excluded.currency, official_languages = excluded.official_languages;
